Repository ctu-mrs/simulation, pull requests merged in 2020-05, with the labels that each got.

#6 Making the upgrade more specific
  installation/install.sh
Labels: objection

#8 updated submodules
  .gitman.yml
Labels: auto-delete-branch, auto-merge

#9 added compilation of custom mavlink (mavros 1.1.0-compatible)
  .ci/ci_before_install.sh
  installation/dependencies/gazebo.sh
  installation/dependencies/mavros.sh
  installation/install.sh
Labels: auto-delete-branch, auto-merge, auto-squash-merge
